spring:
  datasource:
    url: jdbc:mysql://localhost:3306/school
    username: root
    password: pass@word1
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update

